name: Java CI with Maven

on:
  push:
    branches:
      - rama-eventos  # Se activa cuando haces un push a la rama principal
  pull_request:
    branches:
      - main  # También se activa cuando abres un pull request hacia la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # El entorno donde se ejecutará la acción

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Descarga el código del repositorio
        with:
          ref: 'rama-eventos'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean install -DskipTests  # Compila el proyecto, puedes cambiar a gradle si usas ese

      - name: Run tests
        run: mvn test  # Ejecuta las pruebas unitarias del proyecto

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4  # Actualizado de v2 a v4
        with:
          name: test-report
          path: target/test-*.xml  # Los resultados de las pruebas se pueden cargar como artefactos